default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['JULIET_LESSONS_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: juliet_lessons_development

test:
  <<: *default
  database: juliet_lessons_test

production:
  <<: *default
  database: juliet_lessons_production
  url: <%= ENV['DATABASE_URL'] %>